In [ ]:
import sys
sys.path.insert(0, 'C:\\Users\\david\\Documents\\python_projects\\basic_python-1\\src')
from birds.tb_utils import *
from birds.ebird import *
from birds.tb_db import *

#create_hotspot_tables()

#get_tb_hotspots("Hoboken", 40.745255,-74.034775)
# df = get_tb_goldens("Hoboken", 40.745255,-74.034775,151)

# df

# df = get_tb_goldens("Hoboken3", 40.745255,-74.034775,151)

# df

df = get_tb_goldens("Porto Alegre", -30.03306 -51.23,151)

# df


# df = get_tb_goldens("Home", 40.745255,-74.034775,151)

# df

# df = get_tb_goldens("Syracause", 43.0889,-76.1545,100)

# df


# df = get_tb_goldens("Denver", 39.7392,-104.9849,100)

# df

# df = get_tb_goldens("Colorado Springs",38.83389,-104.82528,100)

# df


# df = get_tb_goldens("Minneapolis",44.980553,-93.270035,100)

# df

# df = get_tb_goldens("Duluth",46.78,-92.11,100)

# df

# df = get_tb_goldens("Manaus",-3.117034,-60.025780,100)
# df

# df = get_tb_goldens("San Luis Brazil",-2.52972,-44.30278,100)
# df



# df = get_tb_goldens("Glen Spey", 41.478611, -74.813611,75)

# df

# df = get_tb_goldens("Harriman", 41.240475, -74.098900,75)

# df



#df = get_tb_goldens("ScottsdalePhoenix", 33.4949, -111.9217, 5)
#df

#df = get_tb_goldens("Los AngelesCA", 34.0549, -118.2426, 5)

#df

# df = get_tb_goldens("Menlo Park", 37.4530, -122.1817, 50)
# df

# df = get_tb_goldens("Sao Paulo", -23.533773, -46.625290, 100)
# df

#df = get_tb_goldens("Belize Airport", 17.5361, -88.3078, 200)
# #df

# # df = get_tb_goldens("Ecuador Airport",0.2233, -78.5141, 200) 
# # df

# # df = get_tb_goldens("Fort Lauderdale Airport",26.1224, -80.1373, 200)
# # df

# # df = get_tb_goldens("Cleveland Airport",41.4993, -81.6944, 200)
# # df

# df = get_tb_goldens("Austin Airport",30.1941, -97.6711, 150)
# df

# df = get_tb_goldens("Dallas Airport",32.8990, -97.0336, 150)
# df

# df = get_tb_goldens("Atlanta Airport",33.6324, -84.4333, 150)
# df

# df = get_tb_goldens("New York JFK Airport",40.6446, -73.7797, 150)
# df

# df = get_tb_goldens("Cartagena Airport",10.4463, -75.5165, 150)
# df

# df = get_tb_goldens("Bogota Airport",4.7010, -74.1461, 150)
# df

# df = get_tb_goldens("Buenos Aires Airport",-34.603722, -58.381592, 150)
# df

# df = get_tb_goldens("Ghana Airport",5.607005, -0.171879, 150)
# df


# df = get_tb_goldens("Ghana Airport",5.607005, -0.171879, 150)
# df

# df = get_tb_goldens("Mt. Pocono",41.0361141, -75.34556, 150)
# df

# df = get_tb_goldens("Liberia",10.630573, -85.439346, 150)
# df

# df = get_tb_goldens("Tulum",20.214788,  -87.430588, 150)
# df

#df = get_optimized_hotspots("Hoboken", 5)
#df

# df = get_tb_goldens("Dallas",32.7767,  -96.7970, 150)
# df

# df = get_tb_goldens("Fort Myers",26.6409,  -81.8606, 150)
# df

# df = get_tb_goldens("Everglades City",25.8582,  -81.3851, 150)
# df

# df = get_tb_goldens("Tarrytown",41.0762,  -73.8587, 150)
# df

# df = get_tb_goldens("Orlando",28.5384,  -81.3789, 150)
# df

# df = get_tb_goldens("Tribeca",40.7163,  -74.0086, 150)
# df

# df = get_tb_goldens("Peniche",39.3603,  -9.3876, 150)
# df

# df = get_tb_goldens("Big Bend",29.127487,  -103.242538, 150)
# df

# df = get_tb_goldens("Atlantic City",39.36415000,  -74.42306000, 150)
# df

# df = get_tb_goldens("Shenandoah National Park",38.700516,  -78.292694, 100)
# df

# df = get_tb_goldens("Bogota",4.70139,  -74.14694, 100)
# df

# df = get_tb_goldens("Armenia",4.4528,  -75.7680, 100)
# df



# 32.7767° N, 96.7970° W

# df = q("DESCRIBE hotspots")
# df



# df = q("SELECT * FROM information_schema.tables")
# df

getting tbhotspots
hotspot table exists
getting ebird hotspots
ebird hotspots
Index(['locId', 'locName', 'countryCode', 'subnational1Code',
       'subnational2Code', 'lat', 'lng', 'latestObsDt', 'numSpeciesAllTime',
       'loc_name', 'distance_miles', 'duration', 'rank'],
      dtype='object')
appending to table
returning
getting last two weeks species
getting ride times
get ride time or cached: Hoboken3 40.7025698 -74.0493536
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '349ba8d9-7b64-4088-9657-005896085043', 'sections': [{'id': 'acd2ad93-00f0-460d-966c-989c70989b89', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:21-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7021783, 'lng': -74.0492001}, 'originalLocation': {'lat': 40.7025697, 'lng': -74.0493537}}}, 'arrival': {'time': '2025-08-23T03:37:39-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1218, 'length': 7347, 'baseDuration': 1126}, 'transport': {'mode': 'car'}}]}]}
Duration: 1218 seconds
Duration: 20 minutes 18 seconds
duration from API is: 1218
get ride time or cached: Hoboken3 40.7715482 -73.9724819
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '7c6ba9da-f36d-4878-965b-f4538bb08274', 'sections': [{'id': '35a95734-1cfe-4e7a-81cf-eaca1e15b284', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:22-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7690699, 'lng': -73.96951}, 'originalLocation': {'lat': 40.7715482, 'lng': -73.9724819}}}, 'arrival': {'time': '2025-08-23T03:35:52-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1110, 'length': 9347, 'baseDuration': 1126}, 'transport': {'mode': 'car'}}]}]}
Duration: 1110 seconds
Duration: 18 minutes 30 seconds
duration from API is: 1110
get ride time or cached: Hoboken3 40.7833 -74.1025167
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '1be8fad7-8a19-4792-bf2b-b2957d749a90', 'sections': [{'id': '8e38b0d3-10a9-40c7-a243-b15cf2371474', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:24-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7872499, 'lng': -74.1016401}, 'originalLocation': {'lat': 40.7833, 'lng': -74.1025167}}}, 'arrival': {'time': '2025-08-23T03:38:21-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1257, 'length': 15382, 'baseDuration': 1329}, 'transport': {'mode': 'car'}}]}]}
Duration: 1257 seconds
Duration: 20 minutes 57 seconds
duration from API is: 1257
get ride time or cached: Hoboken3 40.6885372 -74.0189759
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '3cc0713f-56d8-44c4-950e-d159897f00f9', 'sections': [{'id': 'cde429ef-6d9f-4391-b12e-09a430b91e89', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:25-04:00', 'place': {'type': 'place', 'location': {'lat': 40.70147, 'lng': -74.01163}, 'originalLocation': {'lat': 40.6885372, 'lng': -74.0189759}}}, 'arrival': {'time': '2025-08-23T03:35:48-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1103, 'length': 9509, 'baseDuration': 1081}, 'transport': {'mode': 'car'}}]}]}
Duration: 1103 seconds
Duration: 18 minutes 23 seconds
duration from API is: 1103
get ride time or cached: Hoboken3 40.6602841 -73.9689534
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '626f3101-625d-4f13-8a54-4b99a9f1ab30', 'sections': [{'id': '34c09ec7-adad-46b3-bd30-f6dea1bbc96f', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:26-04:00', 'place': {'type': 'place', 'location': {'lat': 40.65744, 'lng': -73.97408}, 'originalLocation': {'lat': 40.660284, 'lng': -73.9689535}}}, 'arrival': {'time': '2025-08-23T03:41:02-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1416, 'length': 15210, 'baseDuration': 1391}, 'transport': {'mode': 'car'}}]}]}
Duration: 1416 seconds
Duration: 23 minutes 36 seconds
duration from API is: 1416
get ride time or cached: Hoboken3 40.7779667 -73.9697165
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '92421319-28fb-448c-b58a-19f82f005d0f', 'sections': [{'id': 'c71babc8-a950-427c-8703-8b43cd32c67e', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:27-04:00', 'place': {'type': 'place', 'location': {'lat': 40.78094, 'lng': -73.97249}, 'originalLocation': {'lat': 40.7779666, 'lng': -73.9697166}}}, 'arrival': {'time': '2025-08-23T03:36:34-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1147, 'length': 9484, 'baseDuration': 1136}, 'transport': {'mode': 'car'}}]}]}
Duration: 1147 seconds
Duration: 19 minutes 7 seconds
duration from API is: 1147
get ride time or cached: Hoboken3 40.7959347 -74.0498471
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'b52104af-f570-4118-91ff-ad75a81406e3', 'sections': [{'id': 'd6baa3eb-2332-46a9-9592-d075ef603eb5', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:28-04:00', 'place': {'type': 'place', 'location': {'lat': 40.79491, 'lng': -74.0509301}, 'originalLocation': {'lat': 40.7959347, 'lng': -74.0498471}}}, 'arrival': {'time': '2025-08-23T03:32:10-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 882, 'length': 8442, 'baseDuration': 929}, 'transport': {'mode': 'car'}}]}]}
Duration: 882 seconds
Duration: 14 minutes 42 seconds
duration from API is: 882
get ride time or cached: Hoboken3 40.72641 -74.090546
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '68ed59b0-e38a-4e4d-aeb5-884f820b916c', 'sections': [{'id': '2da33b7e-d35d-43eb-85ed-a6d67dc02391', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:29-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7271712, 'lng': -74.0908532}, 'originalLocation': {'lat': 40.72641, 'lng': -74.090546}}}, 'arrival': {'time': '2025-08-23T03:34:46-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1037, 'length': 8854, 'baseDuration': 1072}, 'transport': {'mode': 'car'}}]}]}
Duration: 1037 seconds
Duration: 17 minutes 17 seconds
duration from API is: 1037
get ride time or cached: Hoboken3 40.7512103 -74.0085463
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '6a25e916-03d0-46c5-aa11-6f57221e2e0f', 'sections': [{'id': 'c4962f4d-001b-485a-a163-14c47c3b663a', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:30-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7511493, 'lng': -74.0082694}, 'originalLocation': {'lat': 40.7512103, 'lng': -74.0085463}}}, 'arrival': {'time': '2025-08-23T03:31:10-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 820, 'length': 7487, 'baseDuration': 859}, 'transport': {'mode': 'car'}}]}]}
Duration: 820 seconds
Duration: 13 minutes 40 seconds
duration from API is: 820
get ride time or cached: Hoboken3 40.6996104 -73.9973745
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'c1ea311b-2338-4fd4-a14a-1bae78ba9f4c', 'sections': [{'id': '256ca258-992e-4b1a-a67c-aaa9b7bbebcc', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:32-04:00', 'place': {'type': 'place', 'location': {'lat': 40.69847, 'lng': -73.99722}, 'originalLocation': {'lat': 40.6996103, 'lng': -73.9973746}}}, 'arrival': {'time': '2025-08-23T03:40:10-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1358, 'length': 10737, 'baseDuration': 1367}, 'transport': {'mode': 'car'}}]}]}
Duration: 1358 seconds
Duration: 22 minutes 38 seconds
duration from API is: 1358
get ride time or cached: Hoboken3 40.6523083 -73.9904281
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '0f681951-6920-44ce-9033-215cb8a7afbd', 'sections': [{'id': 'f4fd4d8c-5b9f-4faf-9ec9-671aa073e9d3', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:33-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6523576, 'lng': -73.9904955}, 'originalLocation': {'lat': 40.6523082, 'lng': -73.9904281}}}, 'arrival': {'time': '2025-08-23T03:46:28-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1735, 'length': 14999, 'baseDuration': 1679}, 'transport': {'mode': 'car'}}]}]}
Duration: 1735 seconds
Duration: 28 minutes 55 seconds
duration from API is: 1735
get ride time or cached: Hoboken3 40.7602209 -74.1326919
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '497e80bc-b415-4e3c-ac82-3c31802c801e', 'sections': [{'id': '8c98bdf8-44ae-49cc-b0bf-5908c4175e92', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:34-04:00', 'place': {'type': 'place', 'location': {'lat': 40.76261, 'lng': -74.1356901}, 'originalLocation': {'lat': 40.7602209, 'lng': -74.1326919}}}, 'arrival': {'time': '2025-08-23T03:38:23-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1249, 'length': 13568, 'baseDuration': 1285}, 'transport': {'mode': 'car'}}]}]}
Duration: 1249 seconds
Duration: 20 minutes 49 seconds
duration from API is: 1249
get ride time or cached: Hoboken3 40.6170296 -73.8244561
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'de6d1d36-c6b6-4556-ad92-6583039e9955', 'sections': [{'id': '1e31d79f-dc73-4bc1-9de2-9b003e3eec81', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:35-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6170799, 'lng': -73.8243701}, 'originalLocation': {'lat': 40.6170296, 'lng': -73.8244562}}}, 'arrival': {'time': '2025-08-23T04:04:35-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2820, 'length': 32001, 'baseDuration': 2817}, 'transport': {'mode': 'car'}}]}]}
Duration: 2820 seconds
Duration: 47 minutes 0 seconds
duration from API is: 2820
get ride time or cached: Hoboken3 40.7887808 -73.9219681
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '8b73b5ba-a4b6-48d6-af07-040a0b031bd4', 'sections': [{'id': '17c29b7d-ff62-4767-ab01-f9b8dc9cc36a', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:36-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7886073, 'lng': -73.922111}, 'originalLocation': {'lat': 40.7887807, 'lng': -73.9219681}}}, 'arrival': {'time': '2025-08-23T03:50:19-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1963, 'length': 18575, 'baseDuration': 2034}, 'transport': {'mode': 'car'}}]}]}
Duration: 1963 seconds
Duration: 32 minutes 43 seconds
duration from API is: 1963
get ride time or cached: Hoboken3 40.4392518 -73.9869263
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'bfe2f2c4-0ca0-429f-bd45-7d5cff02fcbc', 'sections': [{'id': '1b8e405c-f266-4426-a758-97e85a7f4072', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:37-04:00', 'place': {'type': 'place', 'location': {'lat': 40.4378704, 'lng': -73.9864807}, 'originalLocation': {'lat': 40.4392518, 'lng': -73.9869264}}}, 'arrival': {'time': '2025-08-23T04:25:15-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 4058, 'length': 81758, 'baseDuration': 4028}, 'transport': {'mode': 'car'}}]}]}
Duration: 4058 seconds
Duration: 67 minutes 38 seconds
duration from API is: 4058
get ride time or cached: Hoboken3 40.785376 -74.1005132
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'bf6cbf77-9b5c-45a5-9116-b3229e756f75', 'sections': [{'id': 'e7c16344-2e1f-4c51-8285-b61f0a0bd605', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:38-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7872499, 'lng': -74.1016401}, 'originalLocation': {'lat': 40.785376, 'lng': -74.1005132}}}, 'arrival': {'time': '2025-08-23T03:38:35-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1257, 'length': 15382, 'baseDuration': 1329}, 'transport': {'mode': 'car'}}]}]}
Duration: 1257 seconds
Duration: 20 minutes 57 seconds
duration from API is: 1257
get ride time or cached: Hoboken3 40.796089 -73.9558947
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '7fb5922b-7cf1-4efd-b3ef-455f72caf628', 'sections': [{'id': '9ad45314-86f6-46d1-9a15-1654faf2992d', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:39-04:00', 'place': {'type': 'place', 'location': {'lat': 40.79829, 'lng': -73.9525601}, 'originalLocation': {'lat': 40.796089, 'lng': -73.9558947}}}, 'arrival': {'time': '2025-08-23T03:44:02-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1583, 'length': 12574, 'baseDuration': 1591}, 'transport': {'mode': 'car'}}]}]}
Duration: 1583 seconds
Duration: 26 minutes 23 seconds
duration from API is: 1583
get ride time or cached: Hoboken3 40.7035452 -74.0159751
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'd599ffc5-116d-484e-927b-d00a80cbba34', 'sections': [{'id': 'dfda93d7-a7a9-493c-b83b-60490fc78417', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:41-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7035203, 'lng': -74.0157036}, 'originalLocation': {'lat': 40.7035451, 'lng': -74.0159751}}}, 'arrival': {'time': '2025-08-23T03:40:41-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1380, 'length': 14930, 'baseDuration': 1381}, 'transport': {'mode': 'car'}}]}]}
Duration: 1380 seconds
Duration: 23 minutes 0 seconds
duration from API is: 1380
get ride time or cached: Hoboken3 40.793165 -74.0943718
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '07d6f3ca-6bd6-43c0-824f-b9909f756a16', 'sections': [{'id': '774cbce3-423a-4f19-8364-8118524ca9df', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:42-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7930999, 'lng': -74.0949801}, 'originalLocation': {'lat': 40.793165, 'lng': -74.0943719}}}, 'arrival': {'time': '2025-08-23T03:36:36-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1134, 'length': 14498, 'baseDuration': 1206}, 'transport': {'mode': 'car'}}]}]}
Duration: 1134 seconds
Duration: 18 minutes 54 seconds
duration from API is: 1134
get ride time or cached: Hoboken3 40.6188482 -73.8307995
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '29329076-9ad1-4539-b5b0-430051ca0f49', 'sections': [{'id': 'd9a510cf-a4e4-4c84-9b04-4ad0f4b027ed', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:43-04:00', 'place': {'type': 'place', 'location': {'lat': 40.61677, 'lng': -73.82459}, 'originalLocation': {'lat': 40.6188482, 'lng': -73.8307996}}}, 'arrival': {'time': '2025-08-23T04:04:55-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2832, 'length': 32047, 'baseDuration': 2829}, 'transport': {'mode': 'car'}}]}]}
Duration: 2832 seconds
Duration: 47 minutes 12 seconds
duration from API is: 2832
get ride time or cached: Hoboken3 40.6553787 -73.9686421
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'b62df5a8-630c-4e5c-bf74-3211d97ff4ca', 'sections': [{'id': 'a65a0b40-1c06-493b-971a-f54c33e43af2', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:44-04:00', 'place': {'type': 'place', 'location': {'lat': 40.65465, 'lng': -73.97326}, 'originalLocation': {'lat': 40.6553786, 'lng': -73.9686422}}}, 'arrival': {'time': '2025-08-23T03:41:54-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1450, 'length': 15889, 'baseDuration': 1421}, 'transport': {'mode': 'car'}}]}]}
Duration: 1450 seconds
Duration: 24 minutes 10 seconds
duration from API is: 1450
get ride time or cached: Hoboken3 40.786003 -73.96196
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'e660c9c4-e5d8-43f8-86cd-4eaf7e276ad0', 'sections': [{'id': '1276f025-a6ea-4f56-80cf-cd48855bf144', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:45-04:00', 'place': {'type': 'place', 'location': {'lat': 40.78818, 'lng': -73.9672301}, 'originalLocation': {'lat': 40.786003, 'lng': -73.96196}}}, 'arrival': {'time': '2025-08-23T03:38:34-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1249, 'length': 10402, 'baseDuration': 1257}, 'transport': {'mode': 'car'}}]}]}
Duration: 1249 seconds
Duration: 20 minutes 49 seconds
duration from API is: 1249
get ride time or cached: Hoboken3 40.8065667 -74.0447833
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': '1bbf3469-21dd-4f87-9670-8f83d252191e', 'sections': [{'id': '72da9f1b-faea-492c-b1d1-421015644eea', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:46-04:00', 'place': {'type': 'place', 'location': {'lat': 40.806, 'lng': -74.0438401}, 'originalLocation': {'lat': 40.8065666, 'lng': -74.0447834}}}, 'arrival': {'time': '2025-08-23T03:36:06-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1100, 'length': 10450, 'baseDuration': 1149}, 'transport': {'mode': 'car'}}]}]}
Duration: 1100 seconds
Duration: 18 minutes 20 seconds
duration from API is: 1100
get ride time or cached: Hoboken3 40.6541609 -74.0204451
duration in cache is: 0.0
getting duration from API
{'routes': [{'id': 'b02d5bf9-8653-447b-930a-db185adb9ddd', 'sections': [{'id': '018468a5-d4eb-4ca9-9545-c7a6a1a30c6e', 'type': 'vehicle', 'departure': {'time': '2025-08-23T03:17:47-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6530599, 'lng': -74.0187301}, 'originalLocation': {'lat': 40.6541608, 'lng': -74.0204452}}}, 'arrival': {'time': '2025-08-23T03:47:31-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451681, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1784, 'length': 18943, 'baseDuration': 1783}, 'transport': {'mode': 'car'}}]}]}
Duration: 1784 seconds
Duration: 29 minutes 44 seconds
duration from API is: 1784
get ride time or cached: Hoboken3 40.7795361 -73.9678896

,locName,numSpeciesAllTime,distance_miles,numSpeciesTwoWeeks,golden_rank,duration2
77,Jamaica Bay Wildlife Refuge--South Garden,243,14.079119,139,176620.906102,0.8
15,Richard W. DeKorte Park--Marsh Discovery Trail,216,4.422591,105,165769.689737,0.3
2,Richard W. DeKorte Park,281,4.418500,105,165769.689737,0.3
84,"Jamaica Bay Wildlife Refuge--East Pond, south end",240,14.228535,132,157532.054795,0.7
12,Jamaica Bay Wildlife Refuge,322,14.154296,132,146806.468085,0.8
...,...,...,...,...,...,...
146,Fort Totten Park,207,13.947096,10,81.558677,0.6
72,Meadowlands IBA--Kearny Marsh East,160,3.719341,3,4.615385,0.3
63,Jersey City Reservoir #3 & Pershing Field Park,107,1.061393,1,0.267062,0.2
126,Meadowlands--Richard Kane Natural Area (restri...,159,5.503819,1,0.162308,0.3
30,Hackensack Meadowlands Conservation and Wildli...,202,4.800938,1,0.130814,0.4

In [10]:
import sys
sys.path.insert(0, 'C:\\Users\\david\\Documents\\python_projects\\basic_python-1\\src')
from birds.tb_utils import *
from birds.ebird import *
from birds.tb_db import *

,locName,numSpeciesAllTime,distance_miles,numSpeciesTwoWeeks,golden_rank,duration2
0,Reserva Ecológica Costanera Sur,348,1.604455,161,1.157459e+06,0.2
1,Reserva Ecológica Ciudad Universitaria - Costa...,277,5.722033,102,2.567439e+05,0.2
47,Museo de la Cárcova-UNA,51,1.750001,72,1.078405e+05,0.2
16,Ceibas--Terraplén,276,79.029951,129,5.568584e+04,1.9
5,Reserva Ribera Norte,245,11.296874,73,4.488658e+04,0.4
...,...,...,...,...,...,...
42,El Chajá,170,57.429768,1,3.306392e-02,1.5
89,La Lucila del Mar,156,170.711294,1,1.386749e-02,3.6
83,Reserva Ecológica de la Ciudad Universitaria UNL,189,243.912072,1,1.153920e-02,4.3
63,San José del Rincón,222,243.389602,1,1.115656e-02,4.5
82,Barra do Quaraí--Estrada Pai Passo,204,305.590528,1,8.286148e-03,6.0

In [7]:
df

,locName,numSpeciesAllTime,distance_miles,numSpeciesTwoWeeks,golden_rank,duration2
77,Jamaica Bay Wildlife Refuge--South Garden,243,14.079119,139,176620.906102,0.8
15,Richard W. DeKorte Park--Marsh Discovery Trail,216,4.422591,105,165769.689737,0.3
2,Richard W. DeKorte Park,281,4.418500,105,165769.689737,0.3
84,"Jamaica Bay Wildlife Refuge--East Pond, south end",240,14.228535,132,157532.054795,0.7
12,Jamaica Bay Wildlife Refuge,322,14.154296,132,146806.468085,0.8
...,...,...,...,...,...,...
146,Fort Totten Park,207,13.947096,10,81.558677,0.6
72,Meadowlands IBA--Kearny Marsh East,160,3.719341,3,4.615385,0.3
63,Jersey City Reservoir #3 & Pershing Field Park,107,1.061393,1,0.267062,0.2
126,Meadowlands--Richard Kane Natural Area (restri...,159,5.503819,1,0.162308,0.3
30,Hackensack Meadowlands Conservation and Wildli...,202,4.800938,1,0.130814,0.4

In [ ]:

import sys
sys.path.insert(0, 'C:\\Users\\david\\Documents\\python_projects\\basic_python-1\\src')
import requests
import pandas as pd
import duckdb
import geocoder 
from geopy.distance import geodesic
from here.here import get_ride_time



pd.set_option('display.max_rows', 100)


api_token = "thhuoviq2hlq" # Replace with your actual API token

#https://api.ebird.org/v2/ref/adjacent/{{regionCode}}

con = duckdb.connect(database='ebird.duckdb')

loc = geocoder.ip('me').latlng
#loc = [37.468319, -122.143936] #palo alto
loc = [40.745255, -74.034775] #hoboken

def q( query: str):
    #con = duckdb.connect(database='ebird.duckdb')
    result = con.execute(query)
    df = result.fetchall()
    df = pd.DataFrame(df, columns=[desc[0] for desc in result.description])

    return df







# def getinfo(loc: str):
#     https://api.ebird.org/v2/ref/hotspot/info/{{locId}}



#get_indigo()
#get_hotspots()

print(f"num species: " + str(get_numspecies_last14(40.702570,-74.049354)))

DEKORTE_LAT = 40.783300
DEKORTE_LON = -74.102517

print(f"num species: " + str(get_numspecies_last14(DEKORTE_LAT,DEKORTE_LON)))

CENTRAL_PARK_LAT = 40.771548
CENTRAL_PARK_LON = -73.972482

print(f"num species: " + str(get_numspecies_last14(CENTRAL_PARK_LAT,CENTRAL_PARK_LON)))


HOBOKEN_LAT = 40.740058
HOBOKEN_LON = -74.025799

print(f"num species: " + str(get_numspecies_last14(HOBOKEN_LAT,HOBOKEN_LON)))


get_num_good_species_last14(CENTRAL_PARK_LAT,CENTRAL_PARK_LON)

In [3]:
df = q("select * from taxonomy")
df

,sciName,comName,speciesCode,category,taxonOrder,bandingCodes,comNameCodes,sciNameCodes,order,familyCode,familyComName,familySciName,reportAs,extinct,extinctYear
0,Struthio camelus,Common Ostrich,ostric2,species,2.0,[],[COOS],[STCA],Struthioniformes,struth1,Ostriches,Struthionidae,None,None,NaN
1,Struthio molybdophanes,Somali Ostrich,ostric3,species,7.0,[],[SOOS],[STMO],Struthioniformes,struth1,Ostriches,Struthionidae,None,None,NaN
2,Struthio camelus/molybdophanes,Common/Somali Ostrich,y00934,slash,8.0,[],"[SOOS, COOS]","[STCA, STMO]",Struthioniformes,struth1,Ostriches,Struthionidae,None,None,NaN
3,Casuarius casuarius,Southern Cassowary,soucas1,species,10.0,[],[SOCA],[CACA],Casuariiformes,casuar1,Cassowaries and Emu,Casuariidae,None,None,NaN
4,Casuarius bennetti,Dwarf Cassowary,dwacas1,species,11.0,[],[DWCA],[CABE],Casuariiformes,casuar1,Cassowaries and Emu,Casuariidae,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17410,Saltator fuliginosus,Black-throated Grosbeak,bltgro2,species,35560.0,[],[BTGR],[SAFU],Passeriformes,thraup2,Tanagers and Allies,Thraupidae,None,None,NaN
17411,Saltator sp.,saltator sp.,saltat1,spuh,35561.0,[],[],[],Passeriformes,thraup2,Tanagers and Allies,Thraupidae,None,None,NaN
17412,Thraupidae sp.,Thraupidae sp.,thraup3,spuh,35562.0,[],[],[],Passeriformes,thraup2,Tanagers and Allies,Thraupidae,None,None,NaN
17413,Passeriformes sp.,passerine sp.,passer1,spuh,35563.0,[],[],[],Passeriformes,None,None,None,None,None,NaN
17414,Aves sp.,bird sp.,bird1,spuh,35564.0,[UNBI],[],[],None,None,None,None,None,None,NaN

In [34]:
def get_num_good_species_last14(lat, lon):
    url = 'https://api.ebird.org/v2/data/obs/geo/recent?back=14&dist=.5&&lat=' + str(lat) + '&lng=' + str(lon)
    headers = {
    "X-eBirdApiToken": api_token
    }

     # Send GET request
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        local_species = response.json()
        local_species_df = pd.json_normalize(local_species)
        return local_species_df
    
    else:
        print("failure")

df = get_num_good_species_last14(CENTRAL_PARK_LAT,CENTRAL_PARK_LON)
df

,speciesCode,comName,sciName,locId,locName,obsDt,howMany,lat,lng,obsValid,obsReviewed,locationPrivate,subId,exoticCategory
0,cangoo,Canada Goose,Branta canadensis,L191106,Central Park,2024-12-27 13:27,276.0,40.771548,-73.972482,True,False,False,S206796390,NaN
1,wooduc,Wood Duck,Aix sponsa,L191106,Central Park,2024-12-27 13:27,7.0,40.771548,-73.972482,True,True,False,S206796390,NaN
2,norsho,Northern Shoveler,Spatula clypeata,L191106,Central Park,2024-12-27 13:27,190.0,40.771548,-73.972482,True,False,False,S206796390,NaN
3,gadwal,Gadwall,Mareca strepera,L191106,Central Park,2024-12-27 13:27,1.0,40.771548,-73.972482,True,False,False,S206796390,NaN
4,mallar3,Mallard,Anas platyrhynchos,L191106,Central Park,2024-12-27 13:27,126.0,40.771548,-73.972482,True,False,False,S206796390,NaN
5,ambduc,American Black Duck,Anas rubripes,L191106,Central Park,2024-12-27 13:27,12.0,40.771548,-73.972482,True,False,False,S206796390,NaN
6,buffle,Bufflehead,Bucephala albeola,L191106,Central Park,2024-12-27 13:27,7.0,40.771548,-73.972482,True,False,False,S206796390,NaN
7,hoomer,Hooded Merganser,Lophodytes cucullatus,L191106,Central Park,2024-12-27 13:27,19.0,40.771548,-73.972482,True,False,False,S206796390,NaN
8,commer,Common Merganser,Mergus merganser,L191106,Central Park,2024-12-27 13:27,3.0,40.771548,-73.972482,True,True,False,S206796390,NaN
9,rebmer,Red-breasted Merganser,Mergus serrator,L191106,Central Park,2024-12-27 13:27,4.0,40.771548,-73.972482,True,False,False,S206796390,NaN
10,rudduc,Ruddy Duck,Oxyura jamaicensis,L191106,Central Park,2024-12-27 13:27,89.0,40.771548,-73.972482,True,False,False,S206796390,NaN
11,rocpig,Rock Pigeon,Columba livia,L191106,Central Park,2024-12-27 13:27,3.0,40.771548,-73.972482,True,False,False,S206796390,N
12,moudov,Mourning Dove,Zenaida macroura,L191106,Central Park,2024-12-27 13:27,41.0,40.771548,-73.972482,True,False,False,S206796390,NaN
13,y00475,American Coot,Fulica americana,L191106,Central Park,2024-12-27 13:27,5.0,40.771548,-73.972482,True,False,False,S206796390,NaN
14,ribgul,Ring-billed Gull,Larus delawarensis,L191106,Central Park,2024-12-27 13:27,1000.0,40.771548,-73.972482,True,False,False,S206796390,NaN
15,amhgul1,American Herring Gull,Larus smithsonianus,L191106,Central Park,2024-12-27 13:27,500.0,40.771548,-73.972482,True,False,False,S206796390,NaN
16,gbbgul,Great Black-backed Gull,Larus marinus,L191106,Central Park,2024-12-27 13:27,20.0,40.771548,-73.972482,True,False,False,S206796390,NaN
17,rethaw,Red-tailed Hawk,Buteo jamaicensis,L191106,Central Park,2024-12-27 13:27,2.0,40.771548,-73.972482,True,False,False,S206796390,NaN
18,dowwoo,Downy Woodpecker,Dryobates pubescens,L191106,Central Park,2024-12-27 13:27,1.0,40.771548,-73.972482,True,False,False,S206796390,NaN
19,merlin,Merlin,Falco columbarius,L191106,Central Park,2024-12-27 13:27,1.0,40.771548,-73.972482,True,False,False,S206796390,NaN
20,blujay,Blue Jay,Cyanocitta cristata,L191106,Central Park,2024-12-27 13:27,2.0,40.771548,-73.972482,True,False,False,S206796390,NaN
21,amecro,American Crow,Corvus brachyrhynchos,L191106,Central Park,2024-12-27 13:27,3.0,40.771548,-73.972482,True,False,False,S206796390,NaN
22,fiscro,Fish Crow,Corvus ossifragus,L191106,Central Park,2024-12-27 13:27,1.0,40.771548,-73.972482,True,False,False,S206796390,NaN
23,bkcchi,Black-capped Chickadee,Poecile atricapillus,L191106,Central Park,2024-12-27 13:27,2.0,40.771548,-73.972482,True,False,False,S206796390,NaN
24,tuftit,Tufted Titmouse,Baeolophus bicolor,L191106,Central Park,2024-12-27 13:27,20.0,40.771548,-73.972482,True,False,False,S206796390,NaN
25,whbnut,White-breasted Nuthatch,Sitta carolinensis,L191106,Central Park,2024-12-27 13:27,4.0,40.771548,-73.972482,True,False,False,S206796390,NaN
26,eursta,European Starling,Sturnus vulgaris,L191106,Central Park,2024-12-27 13:27,5.0,40.771548,-73.972482,True,False,False,S206796390,N
27,amerob,American Robin,Turdus migratorius,L191106,Central Park,2024-12-27 13:27,5.0,40.771548,-73.972482,True,False,False,S206796390,NaN
28,houspa,House Sparrow,Passer domesticus,L191106,Central Park,2024-12-27 13:27,32.0,40.771548,-73.972482,True,False,False,S206796390,N
29,whtspa,White-throated Sparrow,Zonotrichia albicollis,L191106,Central Park,2024-12-27 13:27,35.0,40.771548,-73.972482,True,False,False,S206796390,NaN
30,sonspa,Song Sparrow,Melospiza melodia,L191106,Central Park,2024-12-27 13:27,1.0,40.771548,-73.972482,True,False,False,S206796390,NaN
31,norcar,Northern Cardinal,Cardinalis cardinalis,L191106,Central Park,2024-12-27 13:27,2.0,40.771548,-73.972482,True,False,False,S206796390,NaN
32,rebwoo,Red-bellied Woodpecker,Melanerpes carolinus,L1480317,Central Park--The Oven and The Point,2024-12-27 13:17,1.0,40.775626,-73.970054,True,False,False,S206779289,NaN
33,coohaw,Cooper's Hawk,Astur cooperii,L191106,Central Park,2024-12-27 00:30,1.0,40.771548,-73.972482,True,False,False,S206811977,NaN
34,swaspa,Swamp Sparrow,Melospiza georgiana,L191106,Central Park,2024-12-27 00:30,1.0,40.771548,-73.972482,True,False,False,S206811977,NaN
35,comgra,Common Grackle,Quiscalus quiscula,L191106,Central Park,2024-12-27 00:30,NaN,40.771548,-73.972482,True,False,False,S206811977,NaN
36,yebsap,Yellow-bellied Sapsucker,Sphyrapicus varius,L191106,Central Park,2024-12-26 13:22,1.0,40.771548,-73.972482,True,False,False,S206659041,NaN
37,herthr,Hermit Thrush,Catharus guttatus,L191106,Central Park,2024-12-26 13:22,2.0,40.771548,-73.972482,True,False,False,S206659041,NaN
38,daejun,Dark-eyed Junco,Junco hyemalis,L191106,Central Park,2024-12-26 13:22,19.0,40.771548,-73.972482,True,False,False,S206659041,NaN
39,doccor,Double-crested Cormorant,Nannopterum auritum,L191106,Central Park,2024-12-26 13:00,1.0,40.771548,-73.972482,True,False,False,S206695215,NaN
40,rusbla,Rusty Blackbird,Euphagus carolinus,L191106,Central Park,2024-12-26 13:00,1.0,40.771548,-73.972482,True,False,False,S206695215,NaN
41,snogoo,Snow Goose,Anser caerulescens,L191106,Central Park,2024-12-25 15:08,1.0,40.771548,-73.972482,True,True,False,S206556595,NaN
42,foxspa,Fox Sparrow,Passerella iliaca,L191106,Central Park,2024-12-25 15:08,2.0,40.771548,-73.972482,True,False,False,S206556595,NaN
43,brant,Brant,Branta bernicla,L1480317,Central Park--The Oven and The Point,2024-12-25 12:38,1.0,40.775626,-73.970054,True,False,False,S206529046,NaN
44,perfal,Peregrine Falcon,Falco peregrinus,L1480317,Central Park--The Oven and The Point,2024-12-25 12:38,1.0,40.775626,-73.970054,True,False,False,S206529046,NaN
45,houfin,House Finch,Haemorhous mexicanus,L191106,Central Park,2024-12-25 10:15,1.0,40.771548,-73.972482,True,False,False,S206578114,N
46,ruckin,Ruby-crowned Kinglet,Corthylio calendula,L191106,Central Park,2024-12-24 10:26,1.0,40.771548,-73.972482,True,False,False,S206444962,NaN
47,rewbla,Red-winged Blackbird,Agelaius phoeniceus,L191106,Central Park,2024-12-24 10:26,2.0,40.771548,-73.972482,True,False,False,S206444962,NaN
48,grbher3,Great Blue Heron,Ardea herodias,L191106,Central Park,2024-12-23 15:42,1.0,40.771548,-73.972482,True,False,False,S206348975,NaN
49,musduc,Muscovy Duck,Cairina moschata,L38809631,"Wollman Rink, Central Park, New York US-NY (40...",2024-12-23 14:40,3.0,40.767588,-73.974044,True,True,True,S206371445,X
50,rebnut,Red-breasted Nuthatch,Sitta canadensis,L191106,Central Park,2024-12-22 09:30,1.0,40.771548,-73.972482,True,False,False,S206201268,NaN
51,amekes,American Kestrel,Falco sparverius,L191106,Central Park,2024-12-21 09:35,1.0,40.771548,-73.972482,True,False,False,S206091747,NaN
52,shshaw,Sharp-shinned Hawk,Accipiter striatus,L191106,Central Park,2024-12-19 14:31,1.0,40.771548,-73.972482,True,False,False,S205927425,NaN
53,brncre,Brown Creeper,Certhia americana,L191106,Central Park,2024-12-19 06:53,1.0,40.771548,-73.972482,True,False,False,S205952359,NaN
54,gnwtea,Green-winged Teal,Anas crecca,L191106,Central Park,2024-12-18 14:00,2.0,40.771548,-73.972482,True,False,False,S205868585,NaN
55,amegfi,American Goldfinch,Spinus tristis,L191106,Central Park,2024-12-18 14:00,3.0,40.771548,-73.972482,True,False,False,S205868585,NaN
56,carwre,Carolina Wren,Thryothorus ludovicianus,L191106,Central Park,2024-12-18 13:15,1.0,40.771548,-73.972482,True,False,False,S205859683,NaN
57,grycat,Gray Catbird,Dumetella carolinensis,L5465989,Central Park--The Dene (65th-72nd St. E of E D...,2024-12-18 12:25,1.0,40.770762,-73.969542,True,False,False,S206156806,NaN
58,normoc,Northern Mockingbird,Mimus polyglottos,L5465989,Central Park--The Dene (65th-72nd St. E of E D...,2024-12-18 12:25,1.0,40.770762,-73.969542,True,False,False,S206156806,NaN
59,haiwoo,Hairy Woodpecker,Dryobates villosus,L191106,Central Park,2024-12-17 10:23,1.0,40.771548,-73.972482,True,False,False,S205760341,NaN
60,norfli,Northern Flicker,Colaptes auratus,L191106,Central Park,2024-12-17 10:23,1.0,40.771548,-73.972482,True,False,False,S205760341,NaN
61,x00004,Mallard x American Black Duck (hybrid),Anas platyrhynchos x rubripes,L191106,Central Park,2024-12-17 08:52,1.0,40.771548,-73.972482,True,False,False,S205823462,NaN
62,comrav,Common Raven,Corvus corax,L191106,Central Park,2024-12-17 08:52,1.0,40.771548,-73.972482,True,False,False,S205823462,NaN
63,turvul,Turkey Vulture,Cathartes aura,L191106,Central Park,2024-12-15 12:30,1.0,40.771548,-73.972482,True,False,False,S205530452,NaN
64,pinwar,Pine Warbler,Setophaga pinus,L191106,Central Park,2024-12-15 10:23,1.0,40.771548,-73.972482,True,True,False,S205547914,NaN
65,gockin,Golden-crowned Kinglet,Regulus satrapa,L1153696,Central Park--Sheep Meadow,2024-12-15 08:45,1.0,40.771881,-73.974965,True,False,False,S205491090,NaN
66,monpar,Monk Parakeet,Myiopsitta monachus,L191106,Central Park,2024-12-15 08:41,1.0,40.771548,-73.972482,True,True,False,S205497644,N
67,orcwar,Orange-crowned Warbler,Leiothlypis celata,L8262826,Central Park CBC Southeast,2024-12-15 08:30,1.0,40.773639,-73.969122,True,True,True,S205956707,NaN
68,eastow,Eastern Towhee,Pipilo erythrophthalmus,L191106,Central Park,2024-12-15 08:11,1.0,40.771548,-73.972482,True,False,False,S205528651,NaN
69,bnhcow,Brown-headed Cowbird,Molothrus ater,L191106,Central Park,2024-12-15 08:11,1.0,40.771548,-73.972482,True,False,False,S205528651,NaN

In [5]:

#df = q("select locName,lat, lng, subnational1Code, numSpeciesAllTime, distance_miles, rank from loc where  (numSpeciesAllTime > 200) or (distance_miles < 2) order by rank desc limit 20")
df = q("select * from loc where  (numSpeciesAllTime > 200) or (distance_miles < 2) order by rank desc limit 20")

df

,locId,locName,countryCode,subnational1Code,subnational2Code,lat,lng,latestObsDt,numSpeciesAllTime,distance_miles,rank
0,L211437,Stevens Institute of Technology,US,US-NJ,US-NJ-017,40.746651,-74.025400,2024-12-15 08:45,142,0.501358,2832.309711
1,L1392119,Hudson River Park--22nd-29th St.,US,US-NY,US-NY-061,40.751210,-74.008546,2024-12-23 11:48,155,1.436452,1079.047369
2,L189035,Liberty SP,US,US-NJ,US-NJ-017,40.702570,-74.049354,2024-12-27 16:07,304,3.043188,998.952323
3,L1166504,Hudson River Park--Greenwich Village (W Housto...,US,US-NY,US-NY-061,40.735161,-74.010622,2024-12-23 12:27,128,1.446362,884.978715
4,L3246161,Hamilton Park,US,US-NJ,US-NJ-017,40.727503,-74.045384,2024-12-15 14:30,116,1.345574,862.085585
5,L17144832,Hoboken - Pier C,US,US-NJ,US-NJ-017,40.740058,-74.025799,2024-12-15 09:45,49,0.592025,827.667673
6,L191106,Central Park,US,US-NY,US-NY-061,40.771548,-73.972482,2024-12-27 13:27,274,3.738283,732.956896
7,L2617135,Hudson River Park--Tribeca Upland (Chambers to...,US,US-NY,US-NY-061,40.723832,-74.011686,2024-12-27 10:25,140,1.911499,732.409543
8,L10813365,Jersey City Reservoir #3 & Pershing Field Park,US,US-NJ,US-NJ-017,40.741342,-74.054334,2024-12-15 10:30,77,1.061393,725.461926
9,L3044567,"Hudson River Park--Pier 55 (Little Island, W 1...",US,US-NY,US-NY-061,40.742014,-74.010644,2024-12-27 16:19,92,1.285999,715.396982
10,L189040,Lincoln Park West,US,US-NJ,US-NJ-017,40.726410,-74.090546,2024-12-15 10:15,215,3.203098,671.225125
11,L27341969,Hudson River Park--Gansevoort Peninsula,US,US-NY,US-NY-061,40.740016,-74.010893,2024-12-20 12:56,86,1.304464,659.274854
12,L3190548,Jersey City and Harsimus Cemetery,US,US-NJ,US-NJ-017,40.727275,-74.054917,2024-12-27 14:17,105,1.629986,644.177436
13,L389014,Meadowlands IBA--Mill Creek Marsh,US,US-NJ,US-NJ-017,40.795935,-74.049847,2024-12-20 11:10,229,3.585321,638.715447
14,L389007,Richard W. DeKorte Park,US,US-NJ,US-NJ-003,40.783300,-74.102517,2024-12-27 14:42,281,4.418500,635.962407
15,L3872478,Newport Yacht Club and Marina,US,US-NJ,US-NJ-017,40.725780,-74.034926,2024-12-18 15:52,83,1.343813,617.645443
16,L555894,Governors Island (N.Y. County),US,US-NY,US-NY-061,40.688537,-74.018976,2024-12-27 11:14,246,4.000597,614.908255
17,L109518,Central Park--The Ramble,US,US-NY,US-NY-061,40.777967,-73.969717,2024-12-27 15:08,242,4.092243,591.362696
18,L11182164,Canal Park,US,US-NY,US-NY-061,40.725381,-74.010610,2024-12-27 16:15,109,1.868008,583.509199
19,L1902982,Brooklyn Bridge Park,US,US-NY,US-NY-047,40.699610,-73.997375,2024-12-27 13:29,209,3.711470,563.119145

In [7]:
dfa = df[0:100]
dfa['duration'] = dfa.apply(lambda row: get_ride_time(row['lat'], row['lng'], str(loc[0]), str(loc[1])), axis=1)
dfa

{'routes': [{'id': '3adf6989-52b6-449d-afc8-f443b7c1fbbb', 'sections': [{'id': 'fd26a475-7fad-4887-ad44-91d8e9a53294', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:41-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7021783, 'lng': -74.0492003}, 'originalLocation': {'lat': 40.7025697, 'lng': -74.0493537}}}, 'arrival': {'time': '2024-10-05T21:28:50-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1449, 'length': 8172, 'baseDuration': 1238}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1449 seconds
Duration: 24 minutes 9 seconds
{'routes': [{'id': 'e87059e5-e7c8-4afb-8310-0856b5565bb2', 'sections': [{'id': '1e40bfe7-f4e0-4573-892a-d423cffa2e5a', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:42-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7690699, 'lng': -73.96951}, 'originalLocation': {'lat': 40.7715482, 'lng': -73.9724819}}}, 'arrival': {'time': '2024-10-05T21:31:22-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1600, 'length': 9142, 'baseDuration': 1166}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1600 seconds
Duration: 26 minutes 40 seconds
{'routes': [{'id': 'b2303b13-335b-4d96-abbd-b4902eaa7fb9', 'sections': [{'id': 'bfab630a-9346-4cc4-9de4-9e8b476ff8fc', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:43-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7271714, 'lng': -74.0908531}, 'originalLocation': {'lat': 40.72641, 'lng': -74.090546}}}, 'arrival': {'time': '2024-10-05T21:31:36-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1613, 'length': 9195, 'baseDuration': 1206}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1613 seconds
Duration: 26 minutes 53 seconds
{'routes': [{'id': '4faf55b2-e9ab-4857-b1fc-b892844e7583', 'sections': [{'id': '34522e0a-39c8-405e-9b39-0e631e4925d8', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:44-04:00', 'place': {'type': 'place', 'location': {'lat': 40.79491, 'lng': -74.0509301}, 'originalLocation': {'lat': 40.7959347, 'lng': -74.0498471}}}, 'arrival': {'time': '2024-10-05T21:28:03-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1399, 'length': 8402, 'baseDuration': 1111}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1399 seconds
Duration: 23 minutes 19 seconds
{'routes': [{'id': '9bd53247-535d-4f4c-b103-f057ddf279e2', 'sections': [{'id': 'c15e24c4-bc81-4cb7-a57e-86f9fc24c204', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:45-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7872499, 'lng': -74.1016401}, 'originalLocation': {'lat': 40.7833, 'lng': -74.1025167}}}, 'arrival': {'time': '2024-10-05T21:34:31-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1786, 'length': 15383, 'baseDuration': 1321}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1786 seconds
Duration: 29 minutes 46 seconds
{'routes': [{'id': '3f72f6cd-241c-44bd-8fe1-51efcc368ced', 'sections': [{'id': '0b597b2f-26d9-458e-81a7-6d977aab4eb6', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:46-04:00', 'place': {'type': 'place', 'location': {'lat': 40.70147, 'lng': -74.01163}, 'originalLocation': {'lat': 40.6885372, 'lng': -74.0189759}}}, 'arrival': {'time': '2024-10-05T21:27:17-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1351, 'length': 9509, 'baseDuration': 1090}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1351 seconds
Duration: 22 minutes 31 seconds
{'routes': [{'id': 'cda5d366-eafb-4920-9934-8b8582ef2ffc', 'sections': [{'id': 'dce7f823-3522-4e13-a00e-b1cad15ad677', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:47-04:00', 'place': {'type': 'place', 'location': {'lat': 40.78094, 'lng': -73.97249}, 'originalLocation': {'lat': 40.7779666, 'lng': -73.9697166}}}, 'arrival': {'time': '2024-10-05T21:31:30-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1603, 'length': 9279, 'baseDuration': 1175}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1603 seconds
Duration: 26 minutes 43 seconds
{'routes': [{'id': '0c66aad8-e6ac-4299-a2b7-4cedfc5f73ef', 'sections': [{'id': '6f3d16c1-ab13-4214-99cb-aabe17759879', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:49-04:00', 'place': {'type': 'place', 'location': {'lat': 40.69847, 'lng': -73.99722}, 'originalLocation': {'lat': 40.6996103, 'lng': -73.9973746}}}, 'arrival': {'time': '2024-10-05T21:33:29-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1720, 'length': 11547, 'baseDuration': 1427}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1720 seconds
Duration: 28 minutes 40 seconds
{'routes': [{'id': 'c50c5944-5b36-421a-96ed-5100a7f7f122', 'sections': [{'id': '777ba14e-bd49-405b-bb8c-6ef5316da549', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:50-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7872499, 'lng': -74.1016401}, 'originalLocation': {'lat': 40.785376, 'lng': -74.1005132}}}, 'arrival': {'time': '2024-10-05T21:34:36-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1786, 'length': 15383, 'baseDuration': 1321}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1786 seconds
Duration: 29 minutes 46 seconds
{'routes': [{'id': 'b1ed603b-dc73-4466-a257-c4c81dc7a37c', 'sections': [{'id': '4db50420-565f-44df-8af7-9cb16a61d8e3', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:51-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7892351, 'lng': -74.1215556}, 'originalLocation': {'lat': 40.7879827, 'lng': -74.1189195}}}, 'arrival': {'time': '2024-10-05T21:32:47-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1676, 'length': 15044, 'baseDuration': 1348}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1676 seconds
Duration: 27 minutes 56 seconds
{'routes': [{'id': '4997fc4b-91c2-420b-916a-637011d8fd6f', 'sections': [{'id': '96ed71cc-b185-4e10-a020-07132e9431ff', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:52-04:00', 'place': {'type': 'place', 'location': {'lat': 40.76261, 'lng': -74.1356901}, 'originalLocation': {'lat': 40.7602209, 'lng': -74.1326919}}}, 'arrival': {'time': '2024-10-05T21:34:37-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1785, 'length': 15595, 'baseDuration': 1453}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1785 seconds
Duration: 29 minutes 45 seconds
{'routes': [{'id': 'ddde359e-0de9-4c4f-b397-b3376f644260', 'sections': [{'id': 'd8fd8952-204c-4579-b256-6e6a4a61cd9c', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:53-04:00', 'place': {'type': 'place', 'location': {'lat': 40.78818, 'lng': -73.9672301}, 'originalLocation': {'lat': 40.786003, 'lng': -73.96196}}}, 'arrival': {'time': '2024-10-05T21:31:21-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1588, 'length': 12310, 'baseDuration': 1304}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1588 seconds
Duration: 26 minutes 28 seconds
{'routes': [{'id': '44cfd1f4-b57a-4bec-8ce3-2eca88e560d0', 'sections': [{'id': '107d0fa0-b65a-4094-a452-0fde609518fb', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:54-04:00', 'place': {'type': 'place', 'location': {'lat': 40.65744, 'lng': -73.97408}, 'originalLocation': {'lat': 40.660284, 'lng': -73.9689535}}}, 'arrival': {'time': '2024-10-05T21:36:02-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1868, 'length': 15219, 'baseDuration': 1450}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1868 seconds
Duration: 31 minutes 8 seconds
{'routes': [{'id': '8017d906-ef0c-4255-a5de-a19371f6c343', 'sections': [{'id': 'e5a2128c-caf2-40d6-adaa-d38eac4453cd', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:55-04:00', 'place': {'type': 'place', 'location': {'lat': 40.79829, 'lng': -73.9525601}, 'originalLocation': {'lat': 40.796089, 'lng': -73.9558947}}}, 'arrival': {'time': '2024-10-05T21:35:17-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1822, 'length': 14173, 'baseDuration': 1553}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1822 seconds
Duration: 30 minutes 22 seconds
{'routes': [{'id': '1fd28994-38fb-42b4-9a85-55d7bae5ead6', 'sections': [{'id': 'd1931969-cfc7-45b0-a54c-fbbb94f87c26', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:56-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7899373, 'lng': -74.1129079}, 'originalLocation': {'lat': 40.789933, 'lng': -74.1129144}}}, 'arrival': {'time': '2024-10-05T21:34:44-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1788, 'length': 16602, 'baseDuration': 1302}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1788 seconds
Duration: 29 minutes 48 seconds
{'routes': [{'id': '4ebaf58a-cc97-4327-a408-930de1edafba', 'sections': [{'id': '9bfab010-538b-4311-997c-7754135c7ddd', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:58-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7960499, 'lng': -73.96149}, 'originalLocation': {'lat': 40.7949559, 'lng': -73.9572222}}}, 'arrival': {'time': '2024-10-05T21:31:47-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1609, 'length': 12422, 'baseDuration': 1330}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1609 seconds
Duration: 26 minutes 49 seconds
{'routes': [{'id': 'aae1deff-872f-4204-9ef2-a3d278955bb0', 'sections': [{'id': 'aa8851b1-e62b-4a0b-9677-4b0e88c4cd6d', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:04:59-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7886073, 'lng': -73.9221109}, 'originalLocation': {'lat': 40.7887807, 'lng': -73.9219681}}}, 'arrival': {'time': '2024-10-05T21:45:01-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2402, 'length': 26337, 'baseDuration': 2138}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2402 seconds
Duration: 40 minutes 2 seconds
{'routes': [{'id': 'fff5ea37-cd75-4d47-beea-9020a1583a18', 'sections': [{'id': '93d61a77-668f-48f2-b60d-e0eb9ab9d8e9', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:00-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6523576, 'lng': -73.9904955}, 'originalLocation': {'lat': 40.6523082, 'lng': -73.9904281}}}, 'arrival': {'time': '2024-10-05T21:40:23-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2123, 'length': 14982, 'baseDuration': 1704}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2123 seconds
Duration: 35 minutes 23 seconds
{'routes': [{'id': '8682fd97-d22c-4a8d-8218-d1e99b11d43a', 'sections': [{'id': '0734a84f-ef2d-4a35-ae73-1b4fdac9f5ee', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:01-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6624735, 'lng': -74.069827}, 'originalLocation': {'lat': 40.6624917, 'lng': -74.0698136}}}, 'arrival': {'time': '2024-10-05T21:38:45-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2024, 'length': 16010, 'baseDuration': 1497}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2024 seconds
Duration: 33 minutes 44 seconds
{'routes': [{'id': '65767688-a916-44d7-b11e-4e9aee2c88be', 'sections': [{'id': 'ee0f4e6d-ac0d-4651-9583-8c407e3e84a0', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:02-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6813778, 'lng': -74.1150017}, 'originalLocation': {'lat': 40.6818095, 'lng': -74.1146278}}}, 'arrival': {'time': '2024-10-05T21:37:12-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1930, 'length': 13778, 'baseDuration': 1375}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1930 seconds
Duration: 32 minutes 10 seconds
{'routes': [{'id': 'a2c9e7e1-1897-43a2-a25d-d754cb4d8923', 'sections': [{'id': 'f18f3a79-8b77-4d92-ba36-bcead66349de', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:03-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6530599, 'lng': -74.0187301}, 'originalLocation': {'lat': 40.6541608, 'lng': -74.0204452}}}, 'arrival': {'time': '2024-10-05T21:42:07-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2224, 'length': 18944, 'baseDuration': 1772}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2224 seconds
Duration: 37 minutes 4 seconds
{'routes': [{'id': 'df82b38f-ef0a-4a62-b74c-7895d9684a6e', 'sections': [{'id': '013cb4e6-d665-4aba-baef-05d7ec3693b2', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:04-04:00', 'place': {'type': 'place', 'location': {'lat': 40.65465, 'lng': -73.97326}, 'originalLocation': {'lat': 40.6553786, 'lng': -73.9686422}}}, 'arrival': {'time': '2024-10-05T21:36:40-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1896, 'length': 15897, 'baseDuration': 1479}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1896 seconds
Duration: 31 minutes 36 seconds
{'routes': [{'id': 'fe2fb666-af0d-4524-b42d-b1929a7b99c0', 'sections': [{'id': 'eacd408d-90b7-4603-9741-05752b4c196d', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:05-04:00', 'place': {'type': 'place', 'location': {'lat': 40.8397744, 'lng': -74.0391372}, 'originalLocation': {'lat': 40.8389033, 'lng': -74.0388931}}}, 'arrival': {'time': '2024-10-05T21:32:20-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1635, 'length': 15288, 'baseDuration': 1163}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1635 seconds
Duration: 27 minutes 15 seconds
{'routes': [{'id': 'e5084ccc-9766-4e02-bc27-16d08bdecb5e', 'sections': [{'id': 'b5c2ea95-9fbb-42ac-b6bc-052f9445217a', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:07-04:00', 'place': {'type': 'place', 'location': {'lat': 40.8666313, 'lng': -74.0011168}, 'originalLocation': {'lat': 40.8665581, 'lng': -74.0011184}}}, 'arrival': {'time': '2024-10-05T21:35:22-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1815, 'length': 19926, 'baseDuration': 1541}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1815 seconds
Duration: 30 minutes 15 seconds
{'routes': [{'id': 'c5e15f85-92a6-443e-95e3-ecd0f4799884', 'sections': [{'id': '23c240de-5d47-4262-a2ad-6c76c31ec48a', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:08-04:00', 'place': {'type': 'place', 'location': {'lat': 40.86864, 'lng': -73.92559}, 'originalLocation': {'lat': 40.8717025, 'lng': -73.9256904}}}, 'arrival': {'time': '2024-10-05T21:35:26-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 1818, 'length': 19632, 'baseDuration': 1491}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1818 seconds
Duration: 30 minutes 18 seconds
{'routes': [{'id': '98ebd30b-5795-4c2e-9411-16c472fb3e6c', 'sections': [{'id': '55a69764-0813-493b-9ec5-c3cce5cbf898', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:09-04:00', 'place': {'type': 'place', 'location': {'lat': 40.58491, 'lng': -73.99409}, 'originalLocation': {'lat': 40.5848762, 'lng': -73.9945753}}}, 'arrival': {'time': '2024-10-05T21:48:13-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2584, 'length': 27432, 'baseDuration': 2110}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2584 seconds
Duration: 43 minutes 4 seconds
{'routes': [{'id': '87861462-c484-4221-8219-9a29d9bbd61d', 'sections': [{'id': 'b8fd1eec-30f9-4971-b12f-75e0bb352833', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:10-04:00', 'place': {'type': 'place', 'location': {'lat': 40.61891, 'lng': -74.11775}, 'originalLocation': {'lat': 40.6203877, 'lng': -74.1149795}}}, 'arrival': {'time': '2024-10-05T21:42:13-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2223, 'length': 25506, 'baseDuration': 1677}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2223 seconds
Duration: 37 minutes 3 seconds
{'routes': [{'id': 'c5b84b26-cba2-4813-85aa-b52b70210fe2', 'sections': [{'id': '6d2cb962-8aff-4d1a-b1bf-fa65a0ddd504', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:11-04:00', 'place': {'type': 'place', 'location': {'lat': 40.60424, 'lng': -73.9311501}, 'originalLocation': {'lat': 40.599946, 'lng': -73.9243269}}}, 'arrival': {'time': '2024-10-05T21:53:08-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 2877, 'length': 33463, 'baseDuration': 2302}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 2877 seconds
Duration: 47 minutes 57 seconds
{'routes': [{'id': '2817ac3b-a3ae-41b1-8736-4b3b9fcd4538', 'sections': [{'id': '821fe5be-7bf1-415e-ac98-ff94dcdc7f33', 'type': 'vehicle', 'departure': {'time': '2024-10-05T21:05:12-04:00', 'place': {'type': 'place', 'location': {'lat': 40.6170799, 'lng': -73.8243701}, 'originalLocation': {'lat': 40.6170296, 'lng': -73.8244562}}}, 'arrival': {'time': '2024-10-05T22:06:48-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'summary': {'duration': 3696, 'length': 48128, 'baseDuration': 3150}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 3696 seconds
Duration: 61 minutes 36 seconds

C:\Users\david\AppData\Local\Temp\ipykernel_12244\2705453663.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['duration'] = dfa.apply(lambda row: get_ride_time(row['lat'], row['lng'], str(loc[0]), str(loc[1])), axis=1)

,locName,lat,lng,subnational1Code,numSpeciesAllTime,distance_miles,rank,duration
0,Liberty SP,40.702570,-74.049354,US-NJ,303,3.043188,995.666295,1449
1,Central Park,40.771548,-73.972482,US-NY,273,3.738283,730.281871,1600
2,Lincoln Park West,40.726410,-74.090546,US-NJ,215,3.203098,671.225125,1613
3,Meadowlands IBA--Mill Creek Marsh,40.795935,-74.049847,US-NJ,229,3.585321,638.715447,1399
4,Richard W. DeKorte Park,40.783300,-74.102517,US-NJ,280,4.418500,633.699196,1786
5,Governors Island (N.Y. County),40.688537,-74.018976,US-NY,246,4.000597,614.908255,1351
6,Central Park--The Ramble,40.777967,-73.969717,US-NY,242,4.092243,591.362696,1603
7,Brooklyn Bridge Park,40.699610,-73.997375,US-NY,208,3.711470,560.424795,1720
8,Richard W. DeKorte Park--Marsh Discovery Trail,40.785376,-74.100513,US-NJ,210,4.422591,474.834817,1786
9,Meadowlands IBA--Harrier Meadows (restricted a...,40.787983,-74.118919,US-NJ,245,5.308513,461.522840,1676
10,Meadowlands IBA--Kearny Marsh,40.760221,-74.132692,US-NJ,229,5.240848,436.952189,1785
11,Central Park--Jacqueline Kennedy Onassis Reser...,40.786003,-73.961960,US-NY,206,4.743358,434.291448,1588
12,Prospect Park,40.660284,-73.968953,US-NY,293,6.806193,430.490293,1868
13,Central Park--North End (N of 97th St. Transve...,40.796089,-73.955895,US-NY,226,5.424707,416.612375,1822
14,Disposal Rd.,40.789933,-74.112914,US-NJ,210,5.129254,409.416230,1788
15,Central Park--The Ravine (incl. The Loch),40.794956,-73.957222,US-NY,203,5.321078,381.501676,1609
16,Randalls Island,40.788781,-73.921968,US-NY,246,6.636654,370.668726,2402
17,"Green-Wood Cemetery, Brooklyn",40.652308,-73.990428,US-NY,251,6.823280,367.858252,2123
18,Ocean Terminal--The Peninsula,40.662492,-74.069813,US-NJ,218,5.999933,363.337389,2024
19,Stephen R. Gregg County Park,40.681810,-74.114628,US-NJ,215,6.061699,354.686017,1930
20,Bush Terminal Piers Park,40.654161,-74.020445,US-NY,221,6.330572,349.099565,2224
21,Prospect Park--Prospect Lake,40.655379,-73.968642,US-NY,238,7.107892,334.839069,1896
22,Meadowlands IBA--Losen Slote Creek Park,40.838903,-74.038893,US-NJ,211,6.465647,326.340104,1635
23,Overpeck County Park,40.866558,-74.001118,US-NJ,232,8.554322,271.207924,1815
24,Inwood Hill Park,40.871702,-73.925690,US-NY,257,10.432721,246.340336,1818
25,Calvert Vaux Park (Dreier-Offerman Park),40.584876,-73.994575,US-NY,269,11.266179,238.767722,2584
26,Clove Lakes Park,40.620388,-74.114980,US-NY,222,9.590970,231.467734,2223
27,Salt Marsh Nature Center at Marine Park,40.599946,-73.924327,US-NY,265,11.584584,228.752276,2877
28,Jamaica Bay Wildlife Refuge,40.617030,-73.824456,US-NY,322,14.154296,227.492769,3696
29,Coney Island Creek Park,40.581322,-74.005269,US-NY,257,11.417375,225.095517,2723
30,Fort Wadsworth,40.599845,-74.053667,US-NY,224,10.082524,222.166600,2567
31,Floyd Bennett Field,40.592345,-73.891433,US-NY,287,12.963145,221.396890,3067
32,Jamaica Bay Wildlife Refuge--West Pond,40.618848,-73.830799,US-NY,303,13.816089,219.309530,3710
33,Forest Park,40.701323,-73.851337,US-NY,210,10.095858,208.006091,2706
34,Plumb Beach,40.582328,-73.915375,US-NY,267,12.874287,207.390131,2921
35,Flushing Meadows Corona Park--Meadow Lake,40.735188,-73.840475,US-NY,206,10.221249,201.540936,2484
36,Breezy Point Tip,40.550664,-73.935789,US-NY,288,14.399649,200.004879,3509
37,Flushing Meadows Corona Park,40.739798,-73.840783,US-NY,201,10.188045,197.290064,2443
38,Canarsie Beach Park,40.625891,-73.897262,US-NY,215,10.954953,196.258252,3038
39,Jamaica Bay Wildlife Refuge--East Pond,40.622685,-73.822010,US-NY,274,14.015572,195.496842,3578
40,Fort Tilden,40.563281,-73.883312,US-NY,282,14.866775,189.684711,3067
41,Pelham Bay Park,40.868105,-73.809474,US-NY,274,14.539760,188.448781,3445
42,Great Kills Park,40.548145,-74.124195,US-NY,271,14.389926,188.326195,3287
43,Salt Marsh Nature Center at Marine Park--South...,40.593426,-73.923520,US-NY,222,11.996818,185.049069,2916
44,Kissena Park,40.746241,-73.808085,US-NY,218,11.896772,183.242989,2589
45,Shirley Chisholm SP (Fountain Ave. Landfill),40.647279,-73.862473,US-NY,203,11.295547,179.716846,3173
46,Charles Memorial Park,40.649039,-73.833276,US-NY,223,12.492465,178.507608,3478
47,Garret Mountain Reservation (Park),40.899517,-74.179181,US-NJ,231,13.061671,176.853335,2220
48,Miller Field,40.567472,-74.099035,US-NY,221,12.723579,173.693271,3236
49,Jacob Riis Park,40.568813,-73.871055,US-NY,258,14.907810,173.063645,3218
50,Sandy Hook,40.439252,-73.986926,US-NJ,365,21.263941,171.652091,4153
51,Van Cortlandt Park,40.898046,-73.885948,US-NY,221,13.115686,168.500523,2270
52,Pelham Bay Park--Southern Meadow and environs,40.853317,-73.821998,US-NY,226,13.419809,168.407758,2352
53,Jamaica Bay Wildlife Refuge--South Garden,40.617547,-73.825745,US-NY,237,14.079119,168.334399,3648
54,"Jamaica Bay Wildlife Refuge--East Pond, south end",40.617210,-73.822460,US-NY,239,14.228535,167.972323,3617
55,"Jamaica Bay Wildlife Refuge--East Pond, north end",40.632682,-73.823447,US-NY,225,13.547838,166.078163,3509
56,"Jamaica Bay, North Channel Bridge",40.638525,-73.832579,US-NY,205,12.923454,158.626322,3458
57,Sandy Hook--North End,40.476921,-74.010730,US-NJ,293,18.558433,157.879708,4693
58,Dead Horse Point,40.579594,-73.894660,US-NY,212,13.596655,155.920705,2909
59,Fort Tilden--Fishermans Parking Lot,40.557243,-73.898989,US-NY,228,14.806222,153.989313,3209
60,Wolfe's Pond Park,40.514099,-74.191022,US-NY,273,17.940833,152.166850,3316
61,Pelham Bay Park--Orchard Beach & parking lot,40.866126,-73.794305,US-NY,230,15.117405,152.142515,3567
62,Alley Pond Park,40.747387,-73.742952,US-NY,230,15.315321,150.176417,2870
63,Pelham Bay Park--Turtle Cove,40.861911,-73.804956,US-NY,217,14.491627,149.741637,3412
64,Hillview Reservoir (restricted access),40.912379,-73.869606,US-NY,214,14.420074,148.404234,2881
65,Linden Hawk Rise Sanctuary,40.602752,-74.247989,US-NJ,221,14.904951,148.272875,2734
66,Jamaica Bay Wildlife Refuge--North Garden,40.621754,-73.827785,US-NY,203,13.814464,146.947426,3648
67,Fort Tilden--Battery Harris Platform,40.561418,-73.893336,US-NY,216,14.702316,146.915624,3186
68,"Oakwood Beach--tidal marshes, NW to Mill Rd.",40.549490,-74.113169,US-NY,205,14.122424,145.159216,3198
69,Pelham Bay Park--Hunter Island,40.876888,-73.789812,US-NY,225,15.730347,143.035628,3525
70,Great Kills Park--Mudflats,40.546410,-74.118201,US-NY,205,14.404141,142.320188,3285
71,Alley Pond Park--Environmental Center,40.762102,-73.753599,US-NY,210,14.799944,141.892433,2923
72,Sandy Hook--Platform & North Pond,40.471600,-74.005988,US-NJ,268,18.943056,141.476644,4611
73,Great Kills Park--Crookes Point,40.532172,-74.135193,US-NY,221,15.621772,141.469227,3529
74,Alley Pond Park--Oakland Lake,40.758641,-73.759412,US-NY,201,14.479061,138.821156,2961
75,Mt. Loretto Unique Area,40.507290,-74.218032,US-NY,258,19.037720,135.520428,3372
76,Prospect Point,40.867322,-73.709931,US-NY,251,19.001096,132.097646,4171
77,Walker Avenue Wetlands,40.925762,-74.285410,US-NJ,230,18.102089,127.057161,2279
78,The Celery Farm,41.036497,-74.127191,US-NJ,257,20.671442,124.326112,2729
79,Conference House Park,40.499510,-74.251676,US-NY,252,20.434703,123.319632,3281
80,Sandy Hook--Guardian Park & bike path,40.455919,-74.003430,US-NJ,247,20.032405,123.300221,4305
81,Marshlands Conservancy,40.953112,-73.701227,US-NY,273,22.609146,120.747594,3933
82,Troy Meadows Natural Area,40.844139,-74.370832,US-NJ,228,18.897991,120.647748,2686
83,Cemetery of the Resurrection--Perpendicular Pond,40.515480,-74.213696,US-NY,222,18.434826,120.424242,3166
84,Cemetery of the Resurrection,40.517519,-74.212743,US-NY,219,18.288281,119.748814,3074
85,Raritan Bay Waterfront Park & Morgan Avenue Mu...,40.476911,-74.268578,US-NJ,266,22.226061,119.679328,3155
86,Jones Beach SP--West End,40.583587,-73.551435,US-NY,321,27.738317,115.724395,4363
87,Oceanside Marine Nature Study Area,40.623373,-73.624223,US-NY,264,23.147275,114.052302,4268
88,Sands Point Preserve,40.859105,-73.697028,US-NY,218,19.374056,112.521613,4115
89,Piermont Pier,41.042778,-73.897500,US-NY,243,21.752366,111.711985,3552
90,Hempstead Lake SP,40.680481,-73.641562,US-NY,235,21.124053,111.247590,3830
91,Lemon Creek Pier,40.510830,-74.209771,US-NY,206,18.608814,110.700231,3043
92,Sandy Hook--Spermaceti Cove area,40.425944,-73.988285,US-NJ,243,22.167998,109.617474,4152
93,Jones Beach SP--Coast Guard Station,40.588889,-73.556667,US-NY,299,27.339503,109.365557,4410
94,Jones Beach SP,40.594524,-73.510400,US-NY,322,29.448004,109.345270,4316
95,Great Swamp NWR,40.713823,-74.463013,US-NJ,245,22.583564,108.485975,3319
96,Sandy Hook--Horseshoe Cove area,40.446653,-73.996825,US-NJ,219,20.700245,105.795847,4207
97,"Sandy Hook-- K & J Lots, ""Tennis Court""",40.468462,-74.002458,US-NJ,201,19.174425,104.827134,4530
98,Hempstead Lake SP--south end,40.672436,-73.649940,US-NY,218,20.822425,104.694819,3855
99,Edith G. Read Wildlife Sanctuary,40.967174,-73.670184,US-NY,253,24.482176,103.340486,4085

In [9]:
dfa['duration_mins'] = dfa['duration'] / 60

C:\Users\david\AppData\Local\Temp\ipykernel_12244\155877058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['duration_mins'] = dfa['duration'] / 60

In [10]:
dfa

,locName,lat,lng,subnational1Code,numSpeciesAllTime,distance_miles,rank,duration,duration_mins
0,Liberty SP,40.702570,-74.049354,US-NJ,303,3.043188,995.666295,1449,24.150000
1,Central Park,40.771548,-73.972482,US-NY,273,3.738283,730.281871,1600,26.666667
2,Lincoln Park West,40.726410,-74.090546,US-NJ,215,3.203098,671.225125,1613,26.883333
3,Meadowlands IBA--Mill Creek Marsh,40.795935,-74.049847,US-NJ,229,3.585321,638.715447,1399,23.316667
4,Richard W. DeKorte Park,40.783300,-74.102517,US-NJ,280,4.418500,633.699196,1786,29.766667
5,Governors Island (N.Y. County),40.688537,-74.018976,US-NY,246,4.000597,614.908255,1351,22.516667
6,Central Park--The Ramble,40.777967,-73.969717,US-NY,242,4.092243,591.362696,1603,26.716667
7,Brooklyn Bridge Park,40.699610,-73.997375,US-NY,208,3.711470,560.424795,1720,28.666667
8,Richard W. DeKorte Park--Marsh Discovery Trail,40.785376,-74.100513,US-NJ,210,4.422591,474.834817,1786,29.766667
9,Meadowlands IBA--Harrier Meadows (restricted a...,40.787983,-74.118919,US-NJ,245,5.308513,461.522840,1676,27.933333
10,Meadowlands IBA--Kearny Marsh,40.760221,-74.132692,US-NJ,229,5.240848,436.952189,1785,29.750000
11,Central Park--Jacqueline Kennedy Onassis Reser...,40.786003,-73.961960,US-NY,206,4.743358,434.291448,1588,26.466667
12,Prospect Park,40.660284,-73.968953,US-NY,293,6.806193,430.490293,1868,31.133333
13,Central Park--North End (N of 97th St. Transve...,40.796089,-73.955895,US-NY,226,5.424707,416.612375,1822,30.366667
14,Disposal Rd.,40.789933,-74.112914,US-NJ,210,5.129254,409.416230,1788,29.800000
15,Central Park--The Ravine (incl. The Loch),40.794956,-73.957222,US-NY,203,5.321078,381.501676,1609,26.816667
16,Randalls Island,40.788781,-73.921968,US-NY,246,6.636654,370.668726,2402,40.033333
17,"Green-Wood Cemetery, Brooklyn",40.652308,-73.990428,US-NY,251,6.823280,367.858252,2123,35.383333
18,Ocean Terminal--The Peninsula,40.662492,-74.069813,US-NJ,218,5.999933,363.337389,2024,33.733333
19,Stephen R. Gregg County Park,40.681810,-74.114628,US-NJ,215,6.061699,354.686017,1930,32.166667
20,Bush Terminal Piers Park,40.654161,-74.020445,US-NY,221,6.330572,349.099565,2224,37.066667
21,Prospect Park--Prospect Lake,40.655379,-73.968642,US-NY,238,7.107892,334.839069,1896,31.600000
22,Meadowlands IBA--Losen Slote Creek Park,40.838903,-74.038893,US-NJ,211,6.465647,326.340104,1635,27.250000
23,Overpeck County Park,40.866558,-74.001118,US-NJ,232,8.554322,271.207924,1815,30.250000
24,Inwood Hill Park,40.871702,-73.925690,US-NY,257,10.432721,246.340336,1818,30.300000
25,Calvert Vaux Park (Dreier-Offerman Park),40.584876,-73.994575,US-NY,269,11.266179,238.767722,2584,43.066667
26,Clove Lakes Park,40.620388,-74.114980,US-NY,222,9.590970,231.467734,2223,37.050000
27,Salt Marsh Nature Center at Marine Park,40.599946,-73.924327,US-NY,265,11.584584,228.752276,2877,47.950000
28,Jamaica Bay Wildlife Refuge,40.617030,-73.824456,US-NY,322,14.154296,227.492769,3696,61.600000
29,Coney Island Creek Park,40.581322,-74.005269,US-NY,257,11.417375,225.095517,2723,45.383333
30,Fort Wadsworth,40.599845,-74.053667,US-NY,224,10.082524,222.166600,2567,42.783333
31,Floyd Bennett Field,40.592345,-73.891433,US-NY,287,12.963145,221.396890,3067,51.116667
32,Jamaica Bay Wildlife Refuge--West Pond,40.618848,-73.830799,US-NY,303,13.816089,219.309530,3710,61.833333
33,Forest Park,40.701323,-73.851337,US-NY,210,10.095858,208.006091,2706,45.100000
34,Plumb Beach,40.582328,-73.915375,US-NY,267,12.874287,207.390131,2921,48.683333
35,Flushing Meadows Corona Park--Meadow Lake,40.735188,-73.840475,US-NY,206,10.221249,201.540936,2484,41.400000
36,Breezy Point Tip,40.550664,-73.935789,US-NY,288,14.399649,200.004879,3509,58.483333
37,Flushing Meadows Corona Park,40.739798,-73.840783,US-NY,201,10.188045,197.290064,2443,40.716667
38,Canarsie Beach Park,40.625891,-73.897262,US-NY,215,10.954953,196.258252,3038,50.633333
39,Jamaica Bay Wildlife Refuge--East Pond,40.622685,-73.822010,US-NY,274,14.015572,195.496842,3578,59.633333
40,Fort Tilden,40.563281,-73.883312,US-NY,282,14.866775,189.684711,3067,51.116667
41,Pelham Bay Park,40.868105,-73.809474,US-NY,274,14.539760,188.448781,3445,57.416667
42,Great Kills Park,40.548145,-74.124195,US-NY,271,14.389926,188.326195,3287,54.783333
43,Salt Marsh Nature Center at Marine Park--South...,40.593426,-73.923520,US-NY,222,11.996818,185.049069,2916,48.600000
44,Kissena Park,40.746241,-73.808085,US-NY,218,11.896772,183.242989,2589,43.150000
45,Shirley Chisholm SP (Fountain Ave. Landfill),40.647279,-73.862473,US-NY,203,11.295547,179.716846,3173,52.883333
46,Charles Memorial Park,40.649039,-73.833276,US-NY,223,12.492465,178.507608,3478,57.966667
47,Garret Mountain Reservation (Park),40.899517,-74.179181,US-NJ,231,13.061671,176.853335,2220,37.000000
48,Miller Field,40.567472,-74.099035,US-NY,221,12.723579,173.693271,3236,53.933333
49,Jacob Riis Park,40.568813,-73.871055,US-NY,258,14.907810,173.063645,3218,53.633333
50,Sandy Hook,40.439252,-73.986926,US-NJ,365,21.263941,171.652091,4153,69.216667
51,Van Cortlandt Park,40.898046,-73.885948,US-NY,221,13.115686,168.500523,2270,37.833333
52,Pelham Bay Park--Southern Meadow and environs,40.853317,-73.821998,US-NY,226,13.419809,168.407758,2352,39.200000
53,Jamaica Bay Wildlife Refuge--South Garden,40.617547,-73.825745,US-NY,237,14.079119,168.334399,3648,60.800000
54,"Jamaica Bay Wildlife Refuge--East Pond, south end",40.617210,-73.822460,US-NY,239,14.228535,167.972323,3617,60.283333
55,"Jamaica Bay Wildlife Refuge--East Pond, north end",40.632682,-73.823447,US-NY,225,13.547838,166.078163,3509,58.483333
56,"Jamaica Bay, North Channel Bridge",40.638525,-73.832579,US-NY,205,12.923454,158.626322,3458,57.633333
57,Sandy Hook--North End,40.476921,-74.010730,US-NJ,293,18.558433,157.879708,4693,78.216667
58,Dead Horse Point,40.579594,-73.894660,US-NY,212,13.596655,155.920705,2909,48.483333
59,Fort Tilden--Fishermans Parking Lot,40.557243,-73.898989,US-NY,228,14.806222,153.989313,3209,53.483333
60,Wolfe's Pond Park,40.514099,-74.191022,US-NY,273,17.940833,152.166850,3316,55.266667
61,Pelham Bay Park--Orchard Beach & parking lot,40.866126,-73.794305,US-NY,230,15.117405,152.142515,3567,59.450000
62,Alley Pond Park,40.747387,-73.742952,US-NY,230,15.315321,150.176417,2870,47.833333
63,Pelham Bay Park--Turtle Cove,40.861911,-73.804956,US-NY,217,14.491627,149.741637,3412,56.866667
64,Hillview Reservoir (restricted access),40.912379,-73.869606,US-NY,214,14.420074,148.404234,2881,48.016667
65,Linden Hawk Rise Sanctuary,40.602752,-74.247989,US-NJ,221,14.904951,148.272875,2734,45.566667
66,Jamaica Bay Wildlife Refuge--North Garden,40.621754,-73.827785,US-NY,203,13.814464,146.947426,3648,60.800000
67,Fort Tilden--Battery Harris Platform,40.561418,-73.893336,US-NY,216,14.702316,146.915624,3186,53.100000
68,"Oakwood Beach--tidal marshes, NW to Mill Rd.",40.549490,-74.113169,US-NY,205,14.122424,145.159216,3198,53.300000
69,Pelham Bay Park--Hunter Island,40.876888,-73.789812,US-NY,225,15.730347,143.035628,3525,58.750000
70,Great Kills Park--Mudflats,40.546410,-74.118201,US-NY,205,14.404141,142.320188,3285,54.750000
71,Alley Pond Park--Environmental Center,40.762102,-73.753599,US-NY,210,14.799944,141.892433,2923,48.716667
72,Sandy Hook--Platform & North Pond,40.471600,-74.005988,US-NJ,268,18.943056,141.476644,4611,76.850000
73,Great Kills Park--Crookes Point,40.532172,-74.135193,US-NY,221,15.621772,141.469227,3529,58.816667
74,Alley Pond Park--Oakland Lake,40.758641,-73.759412,US-NY,201,14.479061,138.821156,2961,49.350000
75,Mt. Loretto Unique Area,40.507290,-74.218032,US-NY,258,19.037720,135.520428,3372,56.200000
76,Prospect Point,40.867322,-73.709931,US-NY,251,19.001096,132.097646,4171,69.516667
77,Walker Avenue Wetlands,40.925762,-74.285410,US-NJ,230,18.102089,127.057161,2279,37.983333
78,The Celery Farm,41.036497,-74.127191,US-NJ,257,20.671442,124.326112,2729,45.483333
79,Conference House Park,40.499510,-74.251676,US-NY,252,20.434703,123.319632,3281,54.683333
80,Sandy Hook--Guardian Park & bike path,40.455919,-74.003430,US-NJ,247,20.032405,123.300221,4305,71.750000
81,Marshlands Conservancy,40.953112,-73.701227,US-NY,273,22.609146,120.747594,3933,65.550000
82,Troy Meadows Natural Area,40.844139,-74.370832,US-NJ,228,18.897991,120.647748,2686,44.766667
83,Cemetery of the Resurrection--Perpendicular Pond,40.515480,-74.213696,US-NY,222,18.434826,120.424242,3166,52.766667
84,Cemetery of the Resurrection,40.517519,-74.212743,US-NY,219,18.288281,119.748814,3074,51.233333
85,Raritan Bay Waterfront Park & Morgan Avenue Mu...,40.476911,-74.268578,US-NJ,266,22.226061,119.679328,3155,52.583333
86,Jones Beach SP--West End,40.583587,-73.551435,US-NY,321,27.738317,115.724395,4363,72.716667
87,Oceanside Marine Nature Study Area,40.623373,-73.624223,US-NY,264,23.147275,114.052302,4268,71.133333
88,Sands Point Preserve,40.859105,-73.697028,US-NY,218,19.374056,112.521613,4115,68.583333
89,Piermont Pier,41.042778,-73.897500,US-NY,243,21.752366,111.711985,3552,59.200000
90,Hempstead Lake SP,40.680481,-73.641562,US-NY,235,21.124053,111.247590,3830,63.833333
91,Lemon Creek Pier,40.510830,-74.209771,US-NY,206,18.608814,110.700231,3043,50.716667
92,Sandy Hook--Spermaceti Cove area,40.425944,-73.988285,US-NJ,243,22.167998,109.617474,4152,69.200000
93,Jones Beach SP--Coast Guard Station,40.588889,-73.556667,US-NY,299,27.339503,109.365557,4410,73.500000
94,Jones Beach SP,40.594524,-73.510400,US-NY,322,29.448004,109.345270,4316,71.933333
95,Great Swamp NWR,40.713823,-74.463013,US-NJ,245,22.583564,108.485975,3319,55.316667
96,Sandy Hook--Horseshoe Cove area,40.446653,-73.996825,US-NJ,219,20.700245,105.795847,4207,70.116667
97,"Sandy Hook-- K & J Lots, ""Tennis Court""",40.468462,-74.002458,US-NJ,201,19.174425,104.827134,4530,75.500000
98,Hempstead Lake SP--south end,40.672436,-73.649940,US-NY,218,20.822425,104.694819,3855,64.250000
99,Edith G. Read Wildlife Sanctuary,40.967174,-73.670184,US-NY,253,24.482176,103.340486,4085,68.083333

In [53]:
q("select locName, count(*) from obs group by locName having count(*) > 3")

                                              locName  count_star()
0                                                Home             6
1                              Commerce Road Wetlands            12
2             Salt Marsh Nature Center at Marine Park             8
3                               Sandy Hook--North End             6
4                                          Sandy Hook             5
5                                 Hilltop Reservation             6
6                                       Prospect Park             9
7                             Bay Ridge - 86th Street             7
8                                          Cooper Rd.             5
9   Jamaica Bay Wildlife Refuge--East Pond, south end            11
10                                 Ramapo Mountain SF             4
11  Jamaica Bay Wildlife Refuge--East Pond, north end             7
12                  Sandy Hook--Platform & North Pond             4
13                Jones Beach SP--Coast Guard Station             6
14                                Grant Park, Hewlett             5
15           Clay Ave. Wetland (Tessie McNamara Park)             6
16                                       Central Park             8
17                      Green-Wood Cemetery, Brooklyn            12
18                                   Inwood Hill Park            10
19                        Jamaica Bay Wildlife Refuge             7

In [17]:
q("select count(*) from obs")

[(185,)]

In [4]:
import sys



print(sys.path)

hello
{'routes': [{'id': '92ab92a8-df1b-42e3-82df-da16daf270f3', 'sections': [{'id': '237f2094-8910-422a-8d91-31b1c3db9d79', 'type': 'vehicle', 'departure': {'time': '2024-10-05T20:35:32-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7451682, 'lng': -74.0343186}, 'originalLocation': {'lat': 40.7452549, 'lng': -74.034775}}}, 'arrival': {'time': '2024-10-05T20:58:10-04:00', 'place': {'type': 'place', 'location': {'lat': 40.7021782, 'lng': -74.0492005}, 'originalLocation': {'lat': 40.70257, 'lng': -74.049354}}}, 'summary': {'duration': 1358, 'length': 6897, 'baseDuration': 1064}, 'transport': {'mode': 'taxi'}}]}]}
Duration: 1358 seconds
Duration: 22 minutes 38 seconds
1358
['C:\\Users\\david\\Documents\\python_projects\\basic_python-1\\src', '../src', '../src', 'C:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\DLLs', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\lib', '', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32\\lib', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages\\Pythonwin', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages']

['../src', '../src', 'C:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\DLLs', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\lib', '', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32\\lib', 'C:\\Users\\david\\AppData\\Roaming\\Python\\Python310\\site-packages\\Pythonwin', 'c:\\Users\\david\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages']